#!/bin/bash

# ./tests_for ./chapter03/main.ml

set -e

DIR=$(dirname $1)
FILE=$(basename $1)
DEST=${FILE%.ml}_test_examples

cd $DIR
qtest --quiet extract ./$FILE -o ./$DEST.ml
ocamlbuild -quiet -cflags -warn-error,+26 -use-ocamlfind -package oUnit -package qcheck ./$DEST.native
./$DEST.native
cd -
